name: Cache
description: Tarball, Rsync & S3 Cache Kit for Buildkite. Supports Linux, macOS and Windows
author: https://github.com/gencer
requirements:
  - aws
  - tar
  - rsync
configuration:
  properties:
    id:
      type: string
    key:
      type: string
    restore-keys:
      type: [string, array]
    backend:
      type: string
    compress:
      type: [number, boolean]
    compress-program:
      type: [string]
    continue_on_error:
      type: boolean
    pipeline-slug-override:
      type: string
    pr:
      type: boolean
    s3:
      profile:
        type: string
      bucket:
        type: string
      class:
        type: string
      endpoint:
        type: string
      region:
        type: string
      args:
        type: string
      save-cache:
        type: boolean
    tarball:
      path:
        type: string
      max:
        type: number
    rsync:
      path:
        type: string
    paths:
      type: [string, array]
    env:
      type: [string, array]
      minimum: 2
  additionalProperties: false
