name: Cache
description: Tarball, Rsync & S3 Cache Kit for Buildkite. Supports Linux and macOS. (Windows is on the way)
author: https://github.com/gencer
requirements:
  - aws
  - tar
  - rsync
configuration:
  properties:
    id:
      type: string
    key:
      type: string
    restore-keys:
      type: [string, array]
    backend:
      type: string
    pr:
      type: boolean
    s3:
      profile:
        type: string
      bucket:
        type: string
      compress:
        type: [number, boolean]
      class:
        type: string
      endpoint:
        type: string
      region:
        type: string
      args:
        type: string
    tarball:
      path:
        type: string
      compress:
        type: [number, boolean]
      max:
        type: number
    rsync:
      path:
        type: string
    paths:
      type: [string, array]
    env:
      type: [string, array]
      minimum: 2
  additionalProperties: false
